package fr.yezzipe.zelda.items;

import fr.yezzipe.zelda.RandomCollection;
import fr.yezzipe.zelda.items.enums.Ring;

import java.util.HashMap;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class ItemTable {
    private static HashMap<String, RandomCollection<ItemStack>> itemTables = new HashMap<>();

    public static void init() {
	double green = 7.0D;
	double yellow = 5.0D;
	double orange = 3.5D;
	double red = 2.5D;
	RandomCollection<ItemStack> rc1 = new RandomCollection<>();
	rc1.add(red, Ring.TENACITY_RING_2.getRing());
	rc1.add(red, Ring.BURST_RING_2.getRing());
	rc1.add(orange, Ring.BURST_RING_1.getRing());
	rc1.add(orange, Ring.HASTE_RING_2.getRing());
	rc1.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc1.add(yellow, Ring.EVIL_RING_1.getRing());
	rc1.add(yellow, Ring.STATIC_RING_2.getRing());
	rc1.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc1.add(green, Ring.ARMOR_RING_1.getRing());
	rc1.add(green, Ring.STRENGTH_RING_1.getRing());
	rc1.add(100.0D - 2.0D * red - 2.0D * orange - 4.0D * yellow - 2.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/abandoned_mineshaft", rc1);
	RandomCollection<ItemStack> rc2 = new RandomCollection<>();
	rc2.add(red, Ring.ZORA_RING.getRing());
	rc2.add(orange, Ring.HASTE_RING_2.getRing());
	rc2.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc2.add(yellow, Ring.EVIL_RING_1.getRing());
	rc2.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc2.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc2.add(green, Ring.ARMOR_RING_1.getRing());
	rc2.add(green, Ring.STRENGTH_RING_1.getRing());
	rc2.add(green, Ring.FREEZING_RING_1.getRing());
	rc2.add(green, Ring.BURNING_RING_1.getRing());
	rc2.add(100.0D - 1.0D * red - 1.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/buried_treasure", rc2);
	RandomCollection<ItemStack> rc3 = new RandomCollection<>();
	rc3.add(red, Ring.TENACITY_RING_2.getRing());
	rc3.add(red, Ring.BURST_RING_2.getRing());
	rc3.add(orange, Ring.BURST_RING_1.getRing());
	rc3.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc3.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc3.add(yellow, Ring.EVIL_RING_1.getRing());
	rc3.add(yellow, Ring.STATIC_RING_2.getRing());
	rc3.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc3.add(green, Ring.ARMOR_RING_1.getRing());
	rc3.add(green, Ring.STRENGTH_RING_1.getRing());
	rc3.add(100.0D - 2.0D * red - 2.0D * orange - 4.0D * yellow - 2.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/desert_pyramid", rc3);
	RandomCollection<ItemStack> rc4 = new RandomCollection<>();
	rc4.add(red, Ring.GORON_RING.getRing());
	rc4.add(orange, Ring.BURST_RING_1.getRing());
	rc4.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc4.add(orange, Ring.EVIL_RING_2.getRing());
	rc4.add(orange, Ring.FEATHER_RING.getRing());
	rc4.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc4.add(yellow, Ring.EVIL_RING_1.getRing());
	rc4.add(green, Ring.ARMOR_RING_1.getRing());
	rc4.add(green, Ring.STRENGTH_RING_1.getRing());
	rc4.add(green, Ring.FREEZING_RING_1.getRing());
	rc4.add(100.0D - 1.0D * red - 4.0D * orange - 2.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/end_city_treasure", rc4);
	RandomCollection<ItemStack> rc5 = new RandomCollection<>();
	rc5.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc5.add(orange, Ring.EVIL_RING_2.getRing());
	rc5.add(orange, Ring.FEATHER_RING.getRing());
	rc5.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc5.add(yellow, Ring.EVIL_RING_1.getRing());
	rc5.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc5.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc5.add(green, Ring.ARMOR_RING_1.getRing());
	rc5.add(green, Ring.STRENGTH_RING_1.getRing());
	rc5.add(green, Ring.FREEZING_RING_1.getRing());
	rc5.add(100.0D - 0.0D * red - 3.0D * orange - 4.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/igloo_chest", rc5);
	RandomCollection<ItemStack> rc6 = new RandomCollection<>();
	rc6.add(red, Ring.KOKIRI_RING.getRing());
	rc6.add(orange, Ring.BURST_RING_1.getRing());
	rc6.add(orange, Ring.ARMOR_RING_3.getRing());
	rc6.add(yellow, Ring.STATIC_RING_2.getRing());
	rc6.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc6.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc6.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc6.add(green, Ring.ARMOR_RING_1.getRing());
	rc6.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc6.add(green, Ring.FREEZING_RING_1.getRing());
	rc6.add(100.0D - 1.0D * red - 2.0D * orange - 4.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/jungle_temple", rc6);
	RandomCollection<ItemStack> rc7 = new RandomCollection<>();
	rc7.add(red, Ring.GORON_RING.getRing());
	rc7.add(orange, Ring.HASTE_RING_2.getRing());
	rc7.add(orange, Ring.ARMOR_RING_3.getRing());
	rc7.add(yellow, Ring.BURNING_RING_2.getRing());
	rc7.add(yellow, Ring.FLAME_RING_2.getRing());
	rc7.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc7.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc7.add(green, Ring.ARMOR_RING_1.getRing());
	rc7.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc7.add(green, Ring.FREEZING_RING_1.getRing());
	rc7.add(100.0D - 1.0D * red - 2.0D * orange - 4.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/nether_bridge", rc7);
	itemTables.put("minecraft:chests/bastion_bridge", rc7);
	itemTables.put("minecraft:chests/bastion_hoglin_stable", rc7);
	itemTables.put("minecraft:chests/bastion_other", rc7);
	itemTables.put("minecraft:chests/bastion_treasure", rc7);
	RandomCollection<ItemStack> rc8 = new RandomCollection<>();
	rc8.add(red, Ring.BURST_RING_2.getRing());
	rc8.add(red, Ring.KOKIRI_RING.getRing());
	rc8.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc8.add(yellow, Ring.BURNING_RING_2.getRing());
	rc8.add(yellow, Ring.FLAME_RING_2.getRing());
	rc8.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc8.add(green, Ring.ARMOR_RING_1.getRing());
	rc8.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc8.add(green, Ring.FREEZING_RING_1.getRing());
	rc8.add(green, Ring.BURNING_RING_1.getRing());
	rc8.add(100.0D - 2.0D * red - 1.0D * orange - 3.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/pillager_outpost", rc8);
	RandomCollection<ItemStack> rc9 = new RandomCollection<>();
	rc9.add(orange, Ring.FEATHER_RING.getRing());
	rc9.add(orange, Ring.ARMOR_RING_3.getRing());
	rc9.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc9.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc9.add(yellow, Ring.FROST_RING_2.getRing());
	rc9.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc9.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc9.add(green, Ring.ARMOR_RING_1.getRing());
	rc9.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc9.add(green, Ring.FREEZING_RING_1.getRing());
	rc9.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/shipwreck_map", rc9);
	RandomCollection<ItemStack> rc10 = new RandomCollection<>();
	rc10.add(orange, Ring.FEATHER_RING.getRing());
	rc10.add(orange, Ring.ARMOR_RING_3.getRing());
	rc10.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc10.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc10.add(yellow, Ring.FROST_RING_2.getRing());
	rc10.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc10.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc10.add(green, Ring.ARMOR_RING_1.getRing());
	rc10.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc10.add(green, Ring.FREEZING_RING_1.getRing());
	rc10.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/shipwreck_supply", rc10);
	RandomCollection<ItemStack> rc11 = new RandomCollection<>();
	rc11.add(orange, Ring.FEATHER_RING.getRing());
	rc11.add(orange, Ring.ARMOR_RING_3.getRing());
	rc11.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc11.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc11.add(yellow, Ring.FROST_RING_2.getRing());
	rc11.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc11.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc11.add(green, Ring.ARMOR_RING_1.getRing());
	rc11.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc11.add(green, Ring.FREEZING_RING_1.getRing());
	rc11.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/shipwreck_treasure", rc11);
	RandomCollection<ItemStack> rc12 = new RandomCollection<>();
	rc12.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc12.add(orange, Ring.EVIL_RING_2.getRing());
	rc12.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc12.add(yellow, Ring.EVIL_RING_1.getRing());
	rc12.add(yellow, Ring.BURNING_RING_2.getRing());
	rc12.add(yellow, Ring.FLAME_RING_2.getRing());
	rc12.add(green, Ring.ARMOR_RING_1.getRing());
	rc12.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc12.add(green, Ring.FROST_RING_1.getRing());
	rc12.add(green, Ring.BURNING_RING_1.getRing());
	rc12.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/simple_dungeon", rc12);
	RandomCollection<ItemStack> rc13 = new RandomCollection<>();
	rc13.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc13.add(orange, Ring.EVIL_RING_2.getRing());
	rc13.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc13.add(yellow, Ring.EVIL_RING_1.getRing());
	rc13.add(yellow, Ring.BURNING_RING_2.getRing());
	rc13.add(yellow, Ring.FLAME_RING_2.getRing());
	rc13.add(green, Ring.AGILITY_RING.getRing());
	rc13.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc13.add(green, Ring.FROST_RING_1.getRing());
	rc13.add(green, Ring.BURNING_RING_1.getRing());
	rc13.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/stronghold_corridor", rc13);
	RandomCollection<ItemStack> rc14 = new RandomCollection<>();
	rc14.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc14.add(orange, Ring.EVIL_RING_2.getRing());
	rc14.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc14.add(yellow, Ring.EVIL_RING_1.getRing());
	rc14.add(yellow, Ring.BURNING_RING_2.getRing());
	rc14.add(yellow, Ring.FLAME_RING_2.getRing());
	rc14.add(green, Ring.AGILITY_RING.getRing());
	rc14.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc14.add(green, Ring.FROST_RING_1.getRing());
	rc14.add(green, Ring.BURNING_RING_1.getRing());
	rc14.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/stronghold_crossing", rc14);
	RandomCollection<ItemStack> rc15 = new RandomCollection<>();
	rc15.add(orange, Ring.OBSCURE_RING_2.getRing());
	rc15.add(orange, Ring.EVIL_RING_2.getRing());
	rc15.add(yellow, Ring.OBSCURE_RING_1.getRing());
	rc15.add(yellow, Ring.EVIL_RING_1.getRing());
	rc15.add(yellow, Ring.BURNING_RING_2.getRing());
	rc15.add(yellow, Ring.FLAME_RING_2.getRing());
	rc15.add(green, Ring.AGILITY_RING.getRing());
	rc15.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc15.add(green, Ring.FROST_RING_1.getRing());
	rc15.add(green, Ring.BURNING_RING_1.getRing());
	rc15.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/stronghold_library", rc15);
	RandomCollection<ItemStack> rc16 = new RandomCollection<>();
	rc16.add(red, Ring.ZORA_RING.getRing());
	rc16.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc16.add(yellow, Ring.FROST_RING_2.getRing());
	rc16.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc16.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc16.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc16.add(green, Ring.AGILITY_RING.getRing());
	rc16.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc16.add(green, Ring.FROST_RING_1.getRing());
	rc16.add(green, Ring.BURNING_RING_1.getRing());
	rc16.add(100.0D - 1.0D * red - 1.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/underwater_ruin_big", rc16);
	RandomCollection<ItemStack> rc17 = new RandomCollection<>();
	rc17.add(red, Ring.ZORA_RING.getRing());
	rc17.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc17.add(yellow, Ring.FROST_RING_2.getRing());
	rc17.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc17.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc17.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc17.add(green, Ring.AGILITY_RING.getRing());
	rc17.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc17.add(green, Ring.FROST_RING_1.getRing());
	rc17.add(green, Ring.BURNING_RING_1.getRing());
	rc17.add(100.0D - 1.0D * red - 1.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/underwater_ruin_small", rc17);
	RandomCollection<ItemStack> rc18 = new RandomCollection<>();
	rc18.add(orange, Ring.TENACITY_RING_1.getRing());
	rc18.add(orange, Ring.ARMOR_RING_3.getRing());
	rc18.add(yellow, Ring.STATIC_RING_2.getRing());
	rc18.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc18.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc18.add(yellow, Ring.ARMOR_RING_2.getRing());
	rc18.add(green, Ring.AGILITY_RING.getRing());
	rc18.add(green, Ring.LIGHTNING_RING_1.getRing());
	rc18.add(green, Ring.FROST_RING_1.getRing());
	rc18.add(green, Ring.BURNING_RING_1.getRing());
	rc18.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_armorer", rc18);
	RandomCollection<ItemStack> rc19 = new RandomCollection<>();
	rc19.add(orange, Ring.TENACITY_RING_1.getRing());
	rc19.add(yellow, Ring.STATIC_RING_2.getRing());
	rc19.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc19.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc19.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc19.add(green, Ring.AGILITY_RING.getRing());
	rc19.add(green, Ring.STATIC_RING_1.getRing());
	rc19.add(green, Ring.FROST_RING_1.getRing());
	rc19.add(green, Ring.BURNING_RING_1.getRing());
	rc19.add(green, Ring.FREEZING_RING_1.getRing());
	rc19.add(100.0D - 0.0D * red - 1.0D * orange - 4.0D * yellow - 5.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_butcher", rc19);
	RandomCollection<ItemStack> rc20 = new RandomCollection<>();
	rc20.add(orange, Ring.BURST_RING_1.getRing());
	rc20.add(orange, Ring.HASTE_RING_2.getRing());
	rc20.add(yellow, Ring.FROST_RING_2.getRing());
	rc20.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc20.add(yellow, Ring.STATIC_RING_2.getRing());
	rc20.add(green, Ring.AGILITY_RING.getRing());
	rc20.add(green, Ring.STATIC_RING_1.getRing());
	rc20.add(green, Ring.FROST_RING_1.getRing());
	rc20.add(green, Ring.FLAME_RING_1.getRing());
	rc20.add(green, Ring.BURNING_RING_1.getRing());
	rc20.add(100.0D - 0.0D * red - 2.0D * orange - 3.0D * yellow - 5.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_cartographer", rc20);
	RandomCollection<ItemStack> rc21 = new RandomCollection<>();
	rc21.add(orange, Ring.RADIANT_RING_2.getRing());
	rc21.add(orange, Ring.LIGHT_RING_2.getRing());
	rc21.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc21.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc21.add(yellow, Ring.STATIC_RING_2.getRing());
	rc21.add(green, Ring.AGILITY_RING.getRing());
	rc21.add(green, Ring.STATIC_RING_1.getRing());
	rc21.add(green, Ring.FROST_RING_1.getRing());
	rc21.add(green, Ring.FLAME_RING_1.getRing());
	rc21.add(green, Ring.BURNING_RING_1.getRing());
	rc21.add(100.0D - 0.0D * red - 2.0D * orange - 3.0D * yellow - 5.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_desert_house", rc21);
	RandomCollection<ItemStack> rc22 = new RandomCollection<>();
	rc22.add(orange, Ring.TENACITY_RING_1.getRing());
	rc22.add(yellow, Ring.STATIC_RING_2.getRing());
	rc22.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc22.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc22.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc22.add(green, Ring.AGILITY_RING.getRing());
	rc22.add(green, Ring.STATIC_RING_1.getRing());
	rc22.add(green, Ring.FROST_RING_1.getRing());
	rc22.add(green, Ring.FLAME_RING_1.getRing());
	rc22.add(green, Ring.FREEZING_RING_1.getRing());
	rc22.add(100.0D - 0.0D * red - 1.0D * orange - 4.0D * yellow - 5.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_fletcher", rc22);
	RandomCollection<ItemStack> rc23 = new RandomCollection<>();
	rc23.add(orange, Ring.TENACITY_RING_1.getRing());
	rc23.add(yellow, Ring.STATIC_RING_2.getRing());
	rc23.add(yellow, Ring.LIGHTNING_RING_2.getRing());
	rc23.add(yellow, Ring.HASTE_RING_1.getRing());
	rc23.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc23.add(green, Ring.AGILITY_RING.getRing());
	rc23.add(green, Ring.STATIC_RING_1.getRing());
	rc23.add(green, Ring.FROST_RING_1.getRing());
	rc23.add(green, Ring.FLAME_RING_1.getRing());
	rc23.add(green, Ring.STRENGTH_RING_1.getRing());
	rc23.add(100.0D - 0.0D * red - 1.0D * orange - 4.0D * yellow - 5.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_mason", rc23);
	RandomCollection<ItemStack> rc24 = new RandomCollection<>();
	rc24.add(orange, Ring.RADIANT_RING_2.getRing());
	rc24.add(orange, Ring.LIGHT_RING_2.getRing());
	rc24.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc24.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc24.add(yellow, Ring.HASTE_RING_1.getRing());
	rc24.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc24.add(green, Ring.AGILITY_RING.getRing());
	rc24.add(green, Ring.STATIC_RING_1.getRing());
	rc24.add(green, Ring.FLAME_RING_1.getRing());
	rc24.add(green, Ring.ARMOR_RING_1.getRing());
	rc24.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_plains_house", rc24);
	RandomCollection<ItemStack> rc25 = new RandomCollection<>();
	rc25.add(orange, Ring.RADIANT_RING_2.getRing());
	rc25.add(orange, Ring.LIGHT_RING_2.getRing());
	rc25.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc25.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc25.add(yellow, Ring.HASTE_RING_1.getRing());
	rc25.add(yellow, Ring.INVISIBILITY_RING.getRing());
	rc25.add(green, Ring.STRENGTH_RING_1.getRing());
	rc25.add(green, Ring.STATIC_RING_1.getRing());
	rc25.add(green, Ring.FLAME_RING_1.getRing());
	rc25.add(green, Ring.AGILITY_RING.getRing());
	rc25.add(100.0D - 0.0D * red - 2.0D * orange - 4.0D * yellow - 4.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_savanna_house", rc25);
	RandomCollection<ItemStack> rc26 = new RandomCollection<>();
	rc26.add(orange, Ring.RADIANT_RING_2.getRing());
	rc26.add(orange, Ring.LIGHT_RING_2.getRing());
	rc26.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc26.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc26.add(yellow, Ring.FROST_RING_2.getRing());
	rc26.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc26.add(yellow, Ring.HASTE_RING_1.getRing());
	rc26.add(green, Ring.STRENGTH_RING_1.getRing());
	rc26.add(green, Ring.STATIC_RING_1.getRing());
	rc26.add(green, Ring.FLAME_RING_1.getRing());
	rc26.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_snowy_house", rc26);
	RandomCollection<ItemStack> rc27 = new RandomCollection<>();
	rc27.add(orange, Ring.RADIANT_RING_2.getRing());
	rc27.add(orange, Ring.LIGHT_RING_2.getRing());
	rc27.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc27.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc27.add(yellow, Ring.FROST_RING_2.getRing());
	rc27.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc27.add(yellow, Ring.HASTE_RING_1.getRing());
	rc27.add(green, Ring.STRENGTH_RING_1.getRing());
	rc27.add(green, Ring.STATIC_RING_1.getRing());
	rc27.add(green, Ring.FLAME_RING_1.getRing());
	rc27.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_taiga_house", rc27);
	RandomCollection<ItemStack> rc28 = new RandomCollection<>();
	rc28.add(orange, Ring.RADIANT_RING_2.getRing());
	rc28.add(orange, Ring.LIGHT_RING_2.getRing());
	rc28.add(yellow, Ring.RADIANT_RING_1.getRing());
	rc28.add(yellow, Ring.LIGHT_RING_1.getRing());
	rc28.add(yellow, Ring.FROST_RING_2.getRing());
	rc28.add(yellow, Ring.FREEZING_RING_2.getRing());
	rc28.add(yellow, Ring.HASTE_RING_1.getRing());
	rc28.add(green, Ring.STRENGTH_RING_1.getRing());
	rc28.add(green, Ring.STATIC_RING_1.getRing());
	rc28.add(green, Ring.FLAME_RING_1.getRing());
	rc28.add(100.0D - 0.0D * red - 2.0D * orange - 5.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_temple", rc28);
	RandomCollection<ItemStack> rc29 = new RandomCollection<>();
	rc29.add(red, Ring.GORON_RING.getRing());
	rc29.add(orange, Ring.TENACITY_RING_1.getRing());
	rc29.add(orange, Ring.HASTE_RING_2.getRing());
	rc29.add(yellow, Ring.BURNING_RING_2.getRing());
	rc29.add(yellow, Ring.FLAME_RING_2.getRing());
	rc29.add(yellow, Ring.HASTE_RING_1.getRing());
	rc29.add(yellow, Ring.STRENGTH_RING_2.getRing());
	rc29.add(green, Ring.STRENGTH_RING_1.getRing());
	rc29.add(green, Ring.STATIC_RING_1.getRing());
	rc29.add(green, Ring.FLAME_RING_1.getRing());
	rc29.add(100.0D - 1.0D * red - 2.0D * orange - 4.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_toolsmith", rc29);
	RandomCollection<ItemStack> rc30 = new RandomCollection<>();
	rc30.add(orange, Ring.TENACITY_RING_1.getRing());
	rc30.add(orange, Ring.BURST_RING_1.getRing());
	rc30.add(orange, Ring.HASTE_RING_2.getRing());
	rc30.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc30.add(yellow, Ring.BURNING_RING_2.getRing());
	rc30.add(yellow, Ring.FLAME_RING_2.getRing());
	rc30.add(yellow, Ring.HASTE_RING_1.getRing());
	rc30.add(green, Ring.STRENGTH_RING_1.getRing());
	rc30.add(green, Ring.STATIC_RING_1.getRing());
	rc30.add(green, Ring.FLAME_RING_1.getRing());
	rc30.add(100.0D - 0.0D * red - 4.0D * orange - 3.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/village/village_weaponsmith", rc30);
	RandomCollection<ItemStack> rc31 = new RandomCollection<>();
	rc31.add(red, Ring.TENACITY_RING_2.getRing());
	rc31.add(red, Ring.KOKIRI_RING.getRing());
	rc31.add(orange, Ring.FEATHER_RING.getRing());
	rc31.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc31.add(yellow, Ring.BURNING_RING_2.getRing());
	rc31.add(yellow, Ring.FLAME_RING_2.getRing());
	rc31.add(yellow, Ring.HASTE_RING_1.getRing());
	rc31.add(green, Ring.STRENGTH_RING_1.getRing());
	rc31.add(green, Ring.FREEZING_RING_1.getRing());
	rc31.add(green, Ring.FLAME_RING_1.getRing());
	rc31.add(100.0D - 2.0D * red - 2.0D * orange - 3.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/woodland_mansion", rc31);
	RandomCollection<ItemStack> rc32 = new RandomCollection<>();
	rc32.add(red, Ring.TENACITY_RING_2.getRing());
	rc32.add(red, Ring.GORON_RING.getRing());
	rc32.add(orange, Ring.FEATHER_RING.getRing());
	rc32.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc32.add(yellow, Ring.BURNING_RING_2.getRing());
	rc32.add(yellow, Ring.FLAME_RING_2.getRing());
	rc32.add(yellow, Ring.HASTE_RING_1.getRing());
	rc32.add(green, Ring.STRENGTH_RING_1.getRing());
	rc32.add(green, Ring.FREEZING_RING_1.getRing());
	rc32.add(green, Ring.FLAME_RING_1.getRing());
	rc32.add(100.0D - 2.0D * red - 2.0D * orange - 3.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/ruined_portal", rc32);
	RandomCollection<ItemStack> rc33 = new RandomCollection<>();
	rc33.add(red, Ring.TENACITY_RING_2.getRing());
	rc33.add(red, Ring.KOKIRI_RING.getRing());
	rc33.add(orange, Ring.FEATHER_RING.getRing());
	rc33.add(orange, Ring.STRENGTH_RING_3.getRing());
	rc33.add(yellow, Ring.BURNING_RING_2.getRing());
	rc33.add(yellow, Ring.FLAME_RING_2.getRing());
	rc33.add(yellow, Ring.HASTE_RING_1.getRing());
	rc33.add(green, Ring.STRENGTH_RING_1.getRing());
	rc33.add(green, Ring.FREEZING_RING_1.getRing());
	rc33.add(green, Ring.FLAME_RING_1.getRing());
	rc33.add(100.0D - 2.0D * red - 2.0D * orange - 3.0D * yellow - 3.0D * green, new ItemStack(Material.AIR));
	itemTables.put("minecraft:chests/ancient_city", rc33);
    }

    public static RandomCollection<ItemStack> get(String lootTable) {
	return itemTables.get(lootTable);
    }
}
