package fr.yezzipe.zelda.items.enums;

public enum Ingredient {
    ACORN(2, FoodBonus.NONE, new int[] {}, new int[] {50,30}),
    AMBER(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    ANCIENT_CORE(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    ANCIENT_GEAR(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    ANCIENT_SCREW(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    ANCIENT_SHAFT(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    ANCIENT_SPRING(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    APPLE(2,FoodBonus.NONE, new int[] {}, new int[] {30}),
    ARMORANTH(0, FoodBonus.TOUGH, new int[] {1,1,1,1,2}, new int[] {50}),
    ARMORED_CARP(4, FoodBonus.TOUGH, new int[] {1,1,2,3,3}, new int[] {50}),
    ARMORED_PORGY(4, FoodBonus.TOUGH, new int[] {1,2,3,3,3}, new int[] {50}),
    BIG_HEARTY_RADISH(16, FoodBonus.HEARTY, new int[] {5}, new int[] {}),
    BIG_HEARTY_TRUFFLE(12,FoodBonus.HEARTY, new int[] {4}, new int[] {}),
    BIRD_EGG(4, FoodBonus.NONE, new int[] {}, new int[] {90,30}),
    BLADED_RHINO_BEETLE(0, FoodBonus.MIGHTY, new int[] {1,1,1,1,1}, new int[] {50}),
    BLUE_NIGHTSHADE(0, FoodBonus.SNEAKY, new int[] {1,1,1,1,1}, new int[] {120}),
    BOKOBLIN_FANG(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    BOKOBLIN_GUTS(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    BOKOBLIN_HORN(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    BRIGHT_EYED_CRAB(4, FoodBonus.ENERGIZING, new int[] {2,5,8,11,14}, new int[] {}),
    CANE_SUGAR(0, FoodBonus.NONE, new int[] {}, new int[] {80,30}),
    CHICKALOO_TREE_NUT(2, FoodBonus.NONE, new int[] {}, new int[] {40,30}),
    CHILLFIN_TROUT(4, FoodBonus.CHILLY, new int[] {1,2,2,2,2}, new int[] {150}),
    CHILLSHROOM(2, FoodBonus.CHILLY, new int[] {1,1,2,2,2}, new int[] {150}),
    CHUCHU_JELLY(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    COLD_DARNER(0, FoodBonus.CHILLY, new int[] {1,1,2,2,2}, new int[] {150}),
    COOL_SAFFLINA(0, FoodBonus.CHILLY, new int[] {1,1,1,1,1}, new int[] {150}),
    COURSER_BEE_HONEY(8, FoodBonus.ENERGIZING, new int[] {2,5,8,11,14}, new int[] {}),
    DIAMOND(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    DINRAALS_CLAW(0, FoodBonus.RANDOM, new int[] {}, new int[] {210,30}),
    DINRAALS_SCALE(0, FoodBonus.RANDOM, new int[] {}, new int[] {90,30}),
    ELECTRIC_DARNER(0, FoodBonus.ELECTRO, new int[] {1,2,3,3,3}, new int[] {150}),
    ELECTRIC_KEESE_WING(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    ELECTRIC_SAFFLINA(0, FoodBonus.ELECTRO, new int[] {1,1,1,2,2}, new int[] {150}),
    ENDURA_CARROT(8, FoodBonus.ENDURING, new int[] {2,4,6,8,10}, new int[] {}),
    ENDURA_SHROOM(4, FoodBonus.ENDURING, new int[] {1,1,1,2,2}, new int[] {}),
    ENERGETIC_RHINO_BEETLE(0, FoodBonus.ENERGIZING, new int[] {8,15,15,15,15}, new int[] {}),
    FAIRY(20, FoodBonus.NONE, new int[] {}, new int[] {30}),
    FAROSHS_CLAW(0, FoodBonus.RANDOM, new int[] {}, new int[] {210,30}),
    FAROSHS_SCALE(0, FoodBonus.RANDOM, new int[] {}, new int[] {90,30}),
    FIREPROOF_LIZARD(0, FoodBonus.FIREPROOF, new int[] {1,1,1,1,1}, new int[] {150}),
    FIRE_KEESE_WING(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    FLEET_LOTUS_SEEDS(2,FoodBonus.HASTY, new int[] {1,1,2,3,3}, new int[] {60}),
    FLINT(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    FORTIFIED_PUMPKIN(2, FoodBonus.TOUGH, new int[] {1,1,2,3,3}, new int[] {50}),
    FRESH_MILK(2, FoodBonus.NONE, new int[] {}, new int[] {80,30}),
    GIANT_ANCIENT_CORE(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    GOAT_BUTTER(0, FoodBonus.NONE, new int[] {}, new int[] {80, 30}),
    GORON_SPICE(0, FoodBonus.NONE, new int[] {}, new int[] {90,30}),
    HEARTY_BASS(8, FoodBonus.HEARTY, new int[] {2}, new int[] {}),
    HEARTY_BLUESHELL_SNAIL(12, FoodBonus.HEARTY, new int[] {3}, new int[] {}),
    HEARTY_DURIAN(12,FoodBonus.HEARTY, new int[] {4}, new int[] {}),
    HEARTY_LIZARD(0, FoodBonus.HEARTY, new int[] {4}, new int[] {}),
    HEARTY_RADISH(10, FoodBonus.HEARTY, new int[] {3}, new int[] {}),
    HEARTY_SALMON(16, FoodBonus.HEARTY, new int[] {4}, new int[] {}),
    HEARTY_TRUFFLE(8,FoodBonus.HEARTY, new int[] {1}, new int[] {}),
    HIGHTAIL_LIZARD(0, FoodBonus.HASTY, new int[] {1,1,1,1,1}, new int[] {60}),
    HINOX_GUTS(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    HINOX_TOENAIL(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    HINOX_TOOTH(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    HOT_FOOTED_FROG(0, FoodBonus.HASTY, new int[] {1,1,2,3,3}, new int[] {60}),
    HYDROMELON(2,FoodBonus.CHILLY, new int[] {1,1,1,1,1}, new int[] {150}),
    HYLIAN_RICE(4, FoodBonus.NONE, new int[] {}, new int[] {60,30}),
    HYLIAN_SHROOM(2,FoodBonus.NONE, new int[] {}, new int[] {30}),
    HYRULE_BASS(4, FoodBonus.NONE, new int[] {}, new int[] {30}),
    HYRULE_HERB(4, FoodBonus.NONE, new int[] {}, new int[] {30}),
    ICE_KEESE_WING(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    ICY_LIZALFOS_TAIL(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    IRONSHELL_CRAB(4, FoodBonus.TOUGH, new int[] {1,1,2,3,3}, new int[] {50}),
    IRONSHROOM(2,FoodBonus.TOUGH, new int[] {1,1,2,3,3}, new int[] {50}),
    KEESE_EYEBALL(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    KEESE_WING(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    LIZALFOS_HORN(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    LIZALFOS_TAIL(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    LIZALFOS_TALON(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    LUMINOUS_STONE(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    LYNEL_GUTS(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    LYNEL_HOOF(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    LYNEL_HORN(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    MIGHTY_BANANAS(2,FoodBonus.MIGHTY, new int[] {1,1,2,3,3}, new int[] {50}),
    MIGHTY_CARP(4, FoodBonus.MIGHTY, new int[] {1,1,2,3,3}, new int[] {50}),
    MIGHTY_PORGY(4, FoodBonus.MIGHTY, new int[] {1,2,3,3,3}, new int[] {50}),
    MIGHTY_THISTLE(0,FoodBonus.MIGHTY, new int[] {1,1,1,1,2}, new int[] {50}),
    MOBLIN_FANG(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    MOBLIN_GUTS(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    MOBLIN_HORN(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    MOLDUGA_FIN(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    MOLDUGA_GUTS(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    MONSTER_EXTRACT(0, FoodBonus.RANDOM, new int[] {}, new int[] {}),
    NAYDRAS_CLAW(0, FoodBonus.RANDOM, new int[] {}, new int[] {210, 30}),
    NAYDRAS_SCALE(0, FoodBonus.RANDOM, new int[] {}, new int[] {90,30}),
    OCTOROK_EYEBALL(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    OCTOROK_TENTACLE(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    OCTO_BALLOON(0, FoodBonus.NONE, new int[] {}, new int[] {70}),
    OPAL(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    PALM_FRUIT(4,FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_BIRD_DRUMSTICK(4, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_BIRD_THIGH(6, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_GOURMET_MEAT(12, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_MEAT(4, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_PRIME_MEAT(6, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAW_WHOLE_BIRD(12, FoodBonus.NONE, new int[] {}, new int[] {30}),
    RAZORCLAW_CRAB(4, FoodBonus.MIGHTY, new int[] {1,1,2,3,3}, new int[] {50}),
    RAZORSHROOM(2, FoodBonus.MIGHTY, new int[] {1,1,2,3,3}, new int[] {50}),
    RED_CHUCHU_JELLY(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    RED_LIZALFOS_TAIL(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    RESTLESS_CRICKET(0, FoodBonus.ENERGIZING, new int[] {1,2,4,5,5}, new int[] {}),
    ROCK_SALT(0, FoodBonus.NONE, new int[] {}, new int[] {60,30}),
    RUBY(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    RUGGED_RHINO_BEETLE(0, FoodBonus.TOUGH, new int[] {1,1,1,1,1}, new int[] {50}),
    RUSHROOM(2,FoodBonus.HASTY, new int[] {1,1,1,1,2}, new int[] {60}),
    SANKE_CARP(4, FoodBonus.NONE, new int[] {}, new int[] {30}),
    SAPPHIRE(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    SHARD_OF_DINRAALS_FANG(0, FoodBonus.RANDOM, new int[] {}, new int[] {630,30}),
    SHARD_OF_DINRAALS_HORN(0, FoodBonus.RANDOM, new int[] {}, new int[] {1800}),
    SHARD_OF_FAROSHS_FANG(0, FoodBonus.RANDOM, new int[] {}, new int[] {630,30}),
    SHARD_OF_FAROSHS_HORN(0, FoodBonus.RANDOM, new int[] {}, new int[] {1800}),
    SHARD_OF_NAYDRAS_FANG(0, FoodBonus.RANDOM, new int[] {}, new int[] {630,30}),
    SHARD_OF_NAYDRAS_HORN(0, FoodBonus.RANDOM, new int[] {}, new int[] {1800}),
    SILENT_PRINCESS(4, FoodBonus.SNEAKY, new int[] {1,2,3,3,3}, new int[] {120}),
    SILENT_SHROOM(2, FoodBonus.SNEAKY, new int[] {1,1,2,2,3}, new int[] {120}),
    SIZZLEFIN_TROUT(4, FoodBonus.SPICY, new int[] {1,2,2,2,2}, new int[] {150}),
    SMOTHERWING_BUTTERFLY(0, FoodBonus.FIREPROOF, new int[] {1,1,1,2,2}, new int[] {150}),
    SNEAKY_RIVER_SNAIL(4, FoodBonus.SNEAKY, new int[] {1,1,1,1,1}, new int[] {120}),
    SPICY_PEPPER(2,FoodBonus.SPICY, new int[] {1,1,1,1,1}, new int[] {150}),
    STAMELLA_SHROOM(2,FoodBonus.ENERGIZING, new int[] {1,2,4,5,7}, new int[] {}),
    STAMINOKA_BASS(4, FoodBonus.ENERGIZING, new int[] {5,11,15,15,15}, new int[] {}),
    STAR_FRAGMENT(0, FoodBonus.RANDOM, new int[] {}, new int[] {30}),
    STEALTHFIN_TROUT(4, FoodBonus.SNEAKY, new int[] {1,1,2,2,3}, new int[] {120}),
    SUMMERWING_BUTTERFLY(0, FoodBonus.SPICY, new int[] {1,1,1,1,1}, new int[] {150}),
    SUNSET_FIREFLY(0, FoodBonus.SNEAKY, new int[] {1,1,1,1,1}, new int[] {120}),
    SUNSHROOM(2, FoodBonus.SPICY, new int[] {1,1,2,2,2}, new int[] {150}),
    SWIFT_CARROT(2, FoodBonus.HASTY, new int[] {1,1,1,1,2}, new int[] {60}),
    SWIFT_VIOLET(0, FoodBonus.HASTY, new int[] {1,1,2,3,3}, new int[] {60}),
    TABANTHA_WHEAT(4, FoodBonus.NONE, new int[] {}, new int[] {60,30}),
    THUNDERWING_BUTTERFLY(0, FoodBonus.ELECTRO, new int[] {1,1,1,2,2}, new int[] {150}),
    TIRELESS_FROG(8, FoodBonus.ENDURING, new int[] {1,2,3,4,4}, new int[] {}),
    TOPAZ(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    VOLTFIN_TROUT(4, FoodBonus.ELECTRO, new int[] {1,3,3,3,3}, new int[] {150}),
    VOLTFRUIT(2,FoodBonus.ELECTRO, new int[] {1,1,1,2,2}, new int[] {150}),
    WARM_DARNER(0, FoodBonus.SPICY, new int[] {1,1,2,2,2}, new int[] {150}),
    WARM_SAFFLINA(0, FoodBonus.SPICY, new int[] {1,1,1,1,1}, new int[] {150}),
    WHITE_CHUCHU_JELLY(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    WILDBERRY(2,FoodBonus.NONE, new int[] {}, new int[] {30}),
    WINTERWING_BUTTERFLY(0, FoodBonus.CHILLY, new int[] {1,1,1,1,1}, new int[] {150}),
    WOOD(0, FoodBonus.NONE, new int[] {}, new int[] {}),
    YELLOW_CHUCHU_JELLY(0, FoodBonus.NONE, new int[] {}, new int[] {110}),
    YELLOW_LIZALFOS_TAIL(0, FoodBonus.NONE, new int[] {}, new int[] {190}),
    ZAPSHROOM(2, FoodBonus.ELECTRO, new int[] {1,2,3,3,3}, new int[] {150});
    
    private final int health;
    private final FoodBonus bonus;
    private final int[] potency;
    private final int[] duration;

    Ingredient(int health, FoodBonus bonus, int[] potency, int[] duration) {
	this.health = health;
	this.bonus = bonus;
	this.potency = potency;
	this.duration = duration;
    }
    
    public int getHealth() {
	return health;
    }
    
    public FoodBonus getBonus() {
	return bonus;
    }
    
    public int[] getPotency() {
	return potency;
    }
    
    public int[] getDuration() {
	return duration;
    }  
}
