package fr.yezzipe.zelda.items.enums;

public enum Ring {
    ARMOR_RING_1, AGILITY_RING, ARMOR_RING_2, INVISIBILITY_RING, ARMOR_RING_3, STRENGTH_RING_1, STRENGTH_RING_2,
    STRENGTH_RING_3, FEATHER_RING, ZORA_RING, GORON_RING, KOKIRI_RING, HASTE_RING_1, HASTE_RING_2, LIGHTNING_RING_1,
    LIGHTNING_RING_2, STATIC_RING_1, STATIC_RING_2, FREEZING_RING_1, FREEZING_RING_2, FROST_RING_1, FROST_RING_2,
    FLAME_RING_1, FLAME_RING_2, BURNING_RING_1, BURNING_RING_2, LIGHT_RING_1, LIGHT_RING_2, RADIANT_RING_1,
    RADIANT_RING_2, EVIL_RING_1, EVIL_RING_2, OBSCURE_RING_1, OBSCURE_RING_2, BURST_RING_1, BURST_RING_2,
    TENACITY_RING_1, TENACITY_RING_2;
}
